# THE OVERMIND PROTOCOL - Prometheus Configuration
# Comprehensive monitoring for AI-enhanced HFT trading system

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'overmind-protocol'
    environment: 'production'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load alerting rules
rule_files:
  - "/etc/prometheus/alert_rules.yml"

# Scrape configurations
scrape_configs:
  # THE OVERMIND PROTOCOL - Main Trading System
  - job_name: 'overmind-trading'
    static_configs:
      - targets: ['overmind-trading:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s  # High frequency for trading metrics
    scrape_timeout: 4s
    params:
      format: ['prometheus']

  # TensorZero Gateway - AI Decision Engine
  - job_name: 'tensorzero-gateway'
    static_configs:
      - targets: ['tensorzero-gateway:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # System Metrics - Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Database Metrics - PostgreSQL
  - job_name: 'postgres-overmind'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis Metrics
  - job_name: 'redis-overmind'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Grafana Monitoring
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

# Remote write configuration for long-term storage (optional)
# remote_write:
#   - url: "https://your-remote-prometheus-endpoint/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"
